

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ConstraintDBEntities : DbContext
{
    public ConstraintDBEntities()
        : base("name=ConstraintDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<ArchiveConstraint> ArchiveConstraints { get; set; }

    public DbSet<CompanyTeam> CompanyTeams { get; set; }

    public DbSet<Constraint> Constraints { get; set; }

    public DbSet<Meeting> Meetings { get; set; }

    public DbSet<MeetingTeam> MeetingTeams { get; set; }

    public DbSet<MontageProductPlan> MontageProductPlans { get; set; }

    public DbSet<Postponement_reasons> Postponement_reasons { get; set; }

    public DbSet<ProductTree> ProductTrees { get; set; }

    public DbSet<Version> Versions { get; set; }

    public DbSet<DelayHistory> DelayHistories { get; set; }

    public DbSet<User> Users { get; set; }

}

}

