
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class DelayHistory
{

    public bool isMarked { get; set; }

    public bool isArchive { get; set; }

    public System.Guid delayID { get; set; }

    public string productCode { get; set; }

    public string delayAmount { get; set; }

    public string delayCode { get; set; }

    public string delayDate { get; set; }

    public string delayReason { get; set; }

    public string delayDetail { get; set; }

    public string companyTeam { get; set; }

    public string chargePerson { get; set; }

    public string madeDate { get; set; }

    public string boundConstraintID { get; set; }

}

}
