
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class MontageProductPlan
{

    public System.Guid montageID { get; set; }

    public string productCode { get; set; }

    public string version { get; set; }

    public string plannedDate { get; set; }

    public string amount { get; set; }

    public string customer { get; set; }

    public string customerType { get; set; }

    public string frame { get; set; }

    public string relevant_month { get; set; }

    public string aboveLine { get; set; }

}

}
