
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Position
{

    public int positionID { get; set; }

    public string materialCode { get; set; }

    public string customerCode { get; set; }

    public string customerText { get; set; }

    public Nullable<System.DateTime> registerDate { get; set; }

    public string delayReason { get; set; }

    public string amount { get; set; }

    public string companyTeam { get; set; }

    public string chargePerson { get; set; }

}

}
