
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Postponement_reasons
{

    public System.Guid delayID { get; set; }

    public string delayName { get; set; }

}

}
