
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Constraint.DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public System.Guid userID { get; set; }

    public string userType { get; set; }

    public string password { get; set; }

    public string email { get; set; }

    public Nullable<bool> isActive { get; set; }

    public Nullable<bool> permissionForConstraint { get; set; }

    public Nullable<System.DateTime> createdTime { get; set; }

    public string userName { get; set; }

}

}
